// <auto-generated/>
// Generated by AsakiUIScriptGenerator

using Asaki.Core.Attributes;
using Asaki.Core.UI;
using Asaki.Unity.Services.UI;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Asaki.Unity.Services.Scene.SceneManagement.Scripts.UI.LoadingScene
{
    public class LoadingPanelWindow : AsakiUIWindow
    {

        #region UI Components

        [AsakiUIBuilder(AsakiUIWidgetType.Image, Name = "BackgroundPanel")]
        [SerializeField]
        private Image backgroundPanel;

        [AsakiUIBuilder(AsakiUIWidgetType.TextMeshPro, Name = "LoadingText")]
        [SerializeField]
        private TMP_Text loadingText;

        [AsakiUIBuilder(AsakiUIWidgetType.TextMeshPro, Name = "ProgressDetails")]
        [SerializeField]
        private TMP_Text progressDetails;

        [AsakiUIBuilder(AsakiUIWidgetType.Slider, Name = "ProgressBar")]
        [SerializeField]
        private Slider progressBar;

        #endregion
    }
}
