// <auto-generated/>
// Generated by AsakiUIScriptGenerator

using Asaki.Core.Attributes;
using Asaki.Core.UI;
using Asaki.Unity.Services.UI;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Game.Scripts.UI.LoginScene
{
    public class LoginPanelWindow : AsakiUIWindow
    {

        #region UI Components

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "LoginPanel_Username", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField loginPanelUsername;

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "LoginPanel_Password", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField loginPanelPassword;

        [AsakiUIBuilder(AsakiUIWidgetType.Button, Name = "LoginPanel_Button")]
        [SerializeField]
        private Button loginPanelButton;

        #endregion
    }
}
