// <auto-generated/>
// Generated by AsakiUIScriptGenerator

using System;
using System.Threading;
using Asaki.Core.Attributes;
using Asaki.Core.Blackboard;
using Asaki.Core.Broker;
using Asaki.Core.Context;
using Asaki.Core.Logging;
using Asaki.Core.Network;
using Asaki.Core.Reactive;
using Asaki.Core.UI;
using Asaki.Generated;
using Asaki.Unity.Extensions;
using Asaki.Unity.Services.Network;
using Asaki.Unity.Services.UI;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Game.Scripts.UI.LoginScene
{
    /// <summary>
    /// 登录数据模型
    /// </summary>
    [AsakiBind]
    [AsakiSave]
    public partial class LoginData
    {
        [AsakiSaveMember]
        public AsakiProperty<string> Username { get; set; } = new();

        [AsakiSaveMember]
        public AsakiProperty<string> Password { get; set; } = new();
    }

    /// <summary>
    /// 用户数据模型
    /// </summary>
    [AsakiSave]
    public partial class UserData
    {
        [AsakiSaveMember]
        public string UserID { get; set; }

        [AsakiSaveMember]
        public string UserNickname { get; set; }
    }

    /// <summary>
    /// 用户登录事件
    /// </summary>
    public struct UserLoginEvent : IAsakiEvent
    {
        public UserData UserData { get; set; }
    }

    /// <summary>
    /// 登录面板窗口
    /// <para>演示了AsakiUIWindow的正确使用方式，包括：</para>
    /// <list type="bullet">
    /// <item><description>依赖注入（通过IAsakiAutoInject）</description></item>
    /// <item><description>数据绑定（通过AsakiProperty）</description></item>
    /// <item><description>网络请求（通过IAsakiWebService）</description></item>
    /// <item><description>事件发布（通过AsakiBroker）</description></item>
    /// </list>
    /// </summary>
    public class LoginPanelWindow : AsakiUIWindow, IAsakiAutoInject, IAsakiInit<IAsakiWebService, IAsakiUIService>
    {
        #region UI Components

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "LoginPanel_Username", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField loginPanelUsername;

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "LoginPanel_Password", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField loginPanelPassword;

        [AsakiUIBuilder(AsakiUIWidgetType.Button, Name = "LoginPanel_Button")]
        [SerializeField]
        private Button loginPanelButton;

        [AsakiUIBuilder(AsakiUIWidgetType.Button, Name = "LoginPanel_To_Register")]
        [SerializeField]
        private Button loginPanelToRegisterButton;

        #endregion

        #region Data & Services

        private LoginData _loginData = new();
        private class LoginRequest : AsakiRequest<LoginData> { }
        private class LoginResponse : AsakiResponse<UserData> { }

        private IAsakiWebService _asakiWebService;
        private IAsakiUIService _asakiUIService;
        private IAsakiObserver<string> _usernameSubscription;
        private IAsakiObserver<string> _passwordSubscription;

        #endregion

        #region Initialization

        /// <summary>
        /// 依赖注入点 - 由框架自动调用
        /// </summary>
        [AsakiInject]
        public void Init(IAsakiWebService webService, IAsakiUIService uiService)
        {
            _asakiWebService = webService;
            _asakiUIService = uiService;

            ALog.Info($"[{nameof(LoginPanelWindow)}] WebService injected successfully.");
        }

        /// <summary>
        /// Awake阶段初始化 - 不依赖框架服务
        /// </summary>
        protected override void OnAwake()
        {
            base.OnAwake();

            // 设置密码输入框类型
            if (loginPanelPassword != null)
            {
                loginPanelPassword.contentType = TMP_InputField.ContentType.Password;
            }
        }

        /// <summary>
        /// 框架就绪后的初始化
        /// </summary>
        protected override void OnStart()
        {
            base.OnStart();

            // 验证服务是否已注入
            if (_asakiWebService == null)
            {
                ALog.Error($"[{nameof(LoginPanelWindow)}] WebService not injected! " +
                           "Make sure the window is created through IAsakiUIService or AsakiUIWindow.Create.");
            }
        }

        #endregion

        #region Lifecycle

        /// <summary>
        /// 组件启用时
        /// </summary>
        protected override void EnableComponent()
        {
            base.EnableComponent();

            // 绑定数据到UI
            _usernameSubscription = _loginData.Username.BindTwoWay(loginPanelUsername);
            _passwordSubscription = _loginData.Password.BindTwoWay(loginPanelPassword);

            // 注册按钮事件
            if (loginPanelButton)
            {
                loginPanelButton.onClick.AddListener(OnLoginBtnClick);
            }

            if (loginPanelToRegisterButton)
            {
                loginPanelToRegisterButton.onClick.AddListener(OnRegisterBtnClick);
            }
        }

        /// <summary>
        /// 组件禁用时
        /// </summary>
        protected override void DisableComponent()
        {
            base.DisableComponent();

            // 解绑数据
            _loginData.Username.Unbind(_usernameSubscription);
            _loginData.Password.Unbind(_passwordSubscription);

            // 注销按钮事件
            if (loginPanelButton)
            {
                loginPanelButton.onClick.RemoveListener(OnLoginBtnClick);
            }

            if (loginPanelToRegisterButton)
            {
                loginPanelToRegisterButton.onClick.RemoveListener(OnRegisterBtnClick);
            }
        }

        /// <summary>
        /// 资源清理
        /// </summary>
        protected override void Cleanup()
        {
            base.Cleanup();

            // 释放响应式属性
            _loginData.Username?.Dispose();
            _loginData.Password?.Dispose();
        }

        #endregion

        #region Event Handlers

        /// <summary>
        /// 登录按钮点击
        /// </summary>
        public async void OnLoginBtnClick()
        {
            if (_asakiWebService == null)
            {
                ALog.Error($"[{nameof(LoginPanelWindow)}] WebService not available. " +
                           "This may happen if the window was not properly initialized.");
                return;
            }

            // 验证输入
            if (string.IsNullOrWhiteSpace(_loginData.Username.Value))
            {
                ALog.Warn($"[{nameof(LoginPanelWindow)}] Username is empty.");
                return;
            }

            if (string.IsNullOrWhiteSpace(_loginData.Password.Value))
            {
                ALog.Warn($"[{nameof(LoginPanelWindow)}] Password is empty.");
                return;
            }

            try
            {
                LoginRequest request = new LoginRequest();
                request.Data = _loginData;

                var response = await _asakiWebService.PostAsync<LoginRequest, LoginResponse>(
                    "api/auth/login",
                    request,
                    this.destroyCancellationToken
                );

                if (response != null && response.IsSuccess && response.Data != null)
                {
                    // 发布登录成功事件
                    AsakiBroker.Publish(new UserLoginEvent { UserData = response.Data });

                    ALog.Info($"[{nameof(LoginPanelWindow)}] Login Success, " +
                              $"UserID: {response.Data.UserID}, " +
                              $"UserNickname: {response.Data.UserNickname}");
                }
                else
                {
                    ALog.Warn($"[{nameof(LoginPanelWindow)}] Login Failed: {response?.Message}");
                }
            }
            catch (OperationCanceledException)
            {
                ALog.Info($"[{nameof(LoginPanelWindow)}] Login request cancelled.");
            }
            catch (Exception ex)
            {
                ALog.Error($"[{nameof(LoginPanelWindow)}] Login error: {ex.Message}");
            }
        }

        private async void OnRegisterBtnClick()
        {
            await _asakiUIService.OpenAsync<RegisterPanelWindow>((int)WindowAssetId.RegisterPanel);
        }


        #endregion

        #region Window Lifecycle

        /// <summary>
        /// 窗口刷新回调
        /// </summary>
        protected override void OnRefresh(object args)
        {
            base.OnRefresh(args);

            // 重置表单数据
            _loginData.Username.Value = string.Empty;
            _loginData.Password.Value = string.Empty;

            ALog.Info($"[{nameof(LoginPanelWindow)}] Window refreshed.");
        }

        /// <summary>
        /// 入场动画
        /// </summary>
        protected override async UniTask PlayEntryAnimation(CancellationToken token)
        {
            // 简单的淡入动画示例
            if (CanvasGroup != null)
            {
                CanvasGroup.alpha = 0;
                float elapsed = 0;
                float duration = 0.2f;

                while (elapsed < duration && !token.IsCancellationRequested)
                {
                    elapsed += Time.deltaTime;
                    CanvasGroup.alpha = Mathf.Clamp01(elapsed / duration);
                    await UniTask.Yield(PlayerLoopTiming.PostLateUpdate, token);
                }

                CanvasGroup.alpha = 1;
            }
        }

        /// <summary>
        /// 离场动画
        /// </summary>
        protected override async UniTask PlayExitAnimation(CancellationToken token)
        {
            // 简单的淡出动画示例
            if (CanvasGroup != null)
            {
                float elapsed = 0;
                float duration = 0.15f;

                while (elapsed < duration && !token.IsCancellationRequested)
                {
                    elapsed += Time.deltaTime;
                    CanvasGroup.alpha = 1 - Mathf.Clamp01(elapsed / duration);
                    await UniTask.Yield(PlayerLoopTiming.PostLateUpdate, token);
                }

                CanvasGroup.alpha = 0;
            }
        }

        #endregion
    }
}
