﻿﻿﻿// <auto-generated/>
// Generated by AsakiUIScriptGenerator

using System.Threading;
using Asaki.Core.Attributes;
using Asaki.Core.Context;
using Asaki.Core.Logging;
using Asaki.Core.Network;
using Asaki.Core.Reactive;
using Asaki.Core.UI;
using Asaki.Generated;
using Asaki.Unity.Extensions;
using Asaki.Unity.Services.Network;
using Asaki.Unity.Services.UI;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Game.Scripts.UI.LoginScene
{
    /// <summary>
    /// 注册数据模型
    /// </summary>
    [AsakiBind]
    [AsakiSave]
    public partial class RegisterData
    {
        [AsakiSaveMember]
        public AsakiProperty<string> Username { get; set; } = new();

        [AsakiSaveMember]
        public AsakiProperty<string> Password { get; set; } = new();
    }

    /// <summary>
    /// 注册面板窗口
    /// <para>演示了AsakiUIWindow的正确使用方式，包括：</para>
    /// <list type="bullet">
    /// <item><description>依赖注入（通过IAsakiAutoInject）</description></item>
    /// <item><description>数据绑定（通过AsakiProperty）</description></item>
    /// <item><description>网络请求（通过IAsakiWebService）</description></item>
    /// <item><description>窗口导航（通过IAsakiUIService）</description></item>
    /// </list>
    /// </summary>
    public class RegisterPanelWindow : AsakiUIWindow, IAsakiAutoInject, IAsakiInit<IAsakiWebService, IAsakiUIService>
    {
        #region UI Components

        [AsakiUIBuilder(AsakiUIWidgetType.Image, Name = "RegisterPanel")]
        [SerializeField]
        private Image registerPanel;

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "RegisterPanel_Username", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField registerPanelUsername;

        [AsakiUIBuilder(AsakiUIWidgetType.InputField, Name = "RegisterPanel_Password", Parent = "InputArea")]
        [SerializeField]
        private TMP_InputField registerPanelPassword;

        [AsakiUIBuilder(AsakiUIWidgetType.Button, Name = "RegisterPanel_Button", Parent = "Button Area")]
        [SerializeField]
        private Button registerPanel1;

        [AsakiUIBuilder(AsakiUIWidgetType.Button, Name = "BackToLoginPanel_Button (1)", Parent = "Button Area")]
        [SerializeField]
        private Button backToLoginPanel;

        #endregion

        #region Data & Services

        private RegisterData _registerData = new();
        private class RegisterRequest : AsakiRequest<RegisterData> { }
        private class RegisterResponse : AsakiResponse { }

        private IAsakiWebService _asakiWebService;
        private IAsakiUIService _asakiUIService;
        private IAsakiObserver<string> _registerUsernameObserver;
        private IAsakiObserver<string> _registerPasswordObserver;

        #endregion

        #region Initialization

        /// <summary>
        /// 依赖注入点 - 由框架自动调用
        /// </summary>
        [AsakiInject]
        public void Init(IAsakiWebService webService, IAsakiUIService uiService)
        {
            _asakiWebService = webService;
            _asakiUIService = uiService;

            ALog.Info($"[{nameof(RegisterPanelWindow)}] Services injected successfully.");
        }

        /// <summary>
        /// Awake阶段初始化 - 不依赖框架服务
        /// </summary>
        protected override void OnAwake()
        {
            base.OnAwake();

            // 初始化本地数据
            _registerData.Username.Value = string.Empty;
            _registerData.Password.Value = string.Empty;

            // 设置密码输入框类型
            if (registerPanelPassword != null)
            {
                registerPanelPassword.contentType = TMP_InputField.ContentType.Password;
            }
        }

        /// <summary>
        /// 框架就绪后的初始化
        /// </summary>
        protected override void OnStart()
        {
            base.OnStart();

            // 验证服务是否已注入
            if (_asakiWebService == null || _asakiUIService == null)
            {
                ALog.Error($"[{nameof(RegisterPanelWindow)}] Services not injected! " +
                           $"Make sure the window is created through IAsakiUIService or AsakiUIWindow.Create.");
            }
        }

        #endregion

        #region Lifecycle

        /// <summary>
        /// 组件启用时
        /// </summary>
        protected override void EnableComponent()
        {
            base.EnableComponent();

            // 绑定数据到UI
            _registerUsernameObserver = _registerData.Username.BindTwoWay(registerPanelUsername);
            _registerPasswordObserver = _registerData.Password.BindTwoWay(registerPanelPassword);

            // 注册按钮事件
            if (registerPanel1 != null)
            {
                registerPanel1.onClick.AddListener(OnRegisterBtnClick);
            }

            if (backToLoginPanel != null)
            {
                backToLoginPanel.onClick.AddListener(OnBackToLoginPanelBtnClick);
            }
        }

        /// <summary>
        /// 组件禁用时
        /// </summary>
        protected override void DisableComponent()
        {
            base.DisableComponent();

            // 解绑数据
            _registerData.Username.Unbind(_registerUsernameObserver);
            _registerData.Password.Unbind(_registerPasswordObserver);

            // 注销按钮事件
            if (registerPanel1 != null)
            {
                registerPanel1.onClick.RemoveListener(OnRegisterBtnClick);
            }

            if (backToLoginPanel != null)
            {
                backToLoginPanel.onClick.RemoveListener(OnBackToLoginPanelBtnClick);
            }
        }

        /// <summary>
        /// 资源清理
        /// </summary>
        protected override void Cleanup()
        {
            base.Cleanup();

            // 释放响应式属性
            _registerData.Username?.Dispose();
            _registerData.Password?.Dispose();
        }

        #endregion

        #region Event Handlers

        /// <summary>
        /// 注册按钮点击
        /// </summary>
        public async void OnRegisterBtnClick()
        {
            if (_asakiWebService == null || _asakiUIService == null)
            {
                ALog.Error($"[{nameof(RegisterPanelWindow)}] Services not available. " +
                           "This may happen if the window was not properly initialized.");
                return;
            }

            // 验证输入
            if (string.IsNullOrWhiteSpace(_registerData.Username.Value))
            {
                ALog.Warn($"[{nameof(RegisterPanelWindow)}] Username is empty.");
                return;
            }

            if (string.IsNullOrWhiteSpace(_registerData.Password.Value))
            {
                ALog.Warn($"[{nameof(RegisterPanelWindow)}] Password is empty.");
                return;
            }

            try
            {
                RegisterResponse response = await _asakiWebService.PostAsync<RegisterRequest, RegisterResponse>(
                    "api/auth/register",
                    new RegisterRequest
                    {
                        Data = _registerData
                    },
                    this.destroyCancellationToken
                );

                if (response == null || response.IsSuccess == false)
                {
                    ALog.Error($"[{nameof(RegisterPanelWindow)}] Register failed: {response?.Message}");
                }
                else
                {
                    ALog.Info($"[{nameof(RegisterPanelWindow)}] Register success");
                    await _asakiUIService.OpenAsync<LoginPanelWindow>((int)WindowAssetId.LoginPanel);
                }
            }
            catch (System.OperationCanceledException)
            {
                ALog.Info($"[{nameof(RegisterPanelWindow)}] Register request cancelled.");
            }
            catch (System.Exception ex)
            {
                ALog.Error($"[{nameof(RegisterPanelWindow)}] Register error: {ex.Message}");
            }
        }

        /// <summary>
        /// 返回登录面板按钮点击
        /// </summary>
        private void OnBackToLoginPanelBtnClick()
        {
            if (_asakiUIService == null)
            {
                ALog.Error($"[{nameof(RegisterPanelWindow)}] UIService not available.");
                return;
            }

            _asakiUIService.OpenAsync<LoginPanelWindow>((int)WindowAssetId.LoginPanel).Forget();
        }

        #endregion

        #region Window Lifecycle

        /// <summary>
        /// 窗口刷新回调
        /// </summary>
        protected override void OnRefresh(object args)
        {
            base.OnRefresh(args);

            // 重置表单数据
            _registerData.Username.Value = string.Empty;
            _registerData.Password.Value = string.Empty;

            ALog.Info($"[{nameof(RegisterPanelWindow)}] Window refreshed.");
        }

        /// <summary>
        /// 入场动画
        /// </summary>
        protected override async UniTask PlayEntryAnimation(CancellationToken token)
        {
            // 简单的淡入动画示例
            if (CanvasGroup != null)
            {
                CanvasGroup.alpha = 0;
                float elapsed = 0;
                float duration = 0.2f;

                while (elapsed < duration && !token.IsCancellationRequested)
                {
                    elapsed += Time.deltaTime;
                    CanvasGroup.alpha = Mathf.Clamp01(elapsed / duration);
                    await UniTask.Yield(PlayerLoopTiming.PostLateUpdate, token);
                }

                CanvasGroup.alpha = 1;
            }
        }

        /// <summary>
        /// 离场动画
        /// </summary>
        protected override async UniTask PlayExitAnimation(CancellationToken token)
        {
            // 简单的淡出动画示例
            if (CanvasGroup != null)
            {
                float elapsed = 0;
                float duration = 0.15f;

                while (elapsed < duration && !token.IsCancellationRequested)
                {
                    elapsed += Time.deltaTime;
                    CanvasGroup.alpha = 1 - Mathf.Clamp01(elapsed / duration);
                    await UniTask.Yield(PlayerLoopTiming.PostLateUpdate, token);
                }

                CanvasGroup.alpha = 0;
            }
        }

        #endregion
    }
}
