using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Asaki.CodeGen.Generators
{
    public static class AsakiConfigRegistryGenerator
    {
        private const string CONFIG_INTERFACE_NAME = "Asaki.Core.DataTable.IAsakiDataTable";

        public static void Execute(GeneratorExecutionContext context, List<ClassDeclarationSyntax> candidateConfigs)
        {
            if (candidateConfigs.Count == 0) return;

            var compilation = context.Compilation;
            var configInterfaceSymbol = compilation.GetTypeByMetadataName(CONFIG_INTERFACE_NAME);
            if (configInterfaceSymbol == null) return;

            var validConfigs = new List<INamedTypeSymbol>();

            foreach (var classDecl in candidateConfigs)
            {
                var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (classSymbol == null || classSymbol.IsAbstract) continue;

                if (classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, configInterfaceSymbol)))
                {
                    validConfigs.Add(classSymbol);
                }
            }

            if (validConfigs.Count > 0)
            {
                string source = GenerateSource(validConfigs);
                context.AddSource("AsakiConfigRegistry.g.cs", source);
            }
        }

        private static string GenerateSource(List<INamedTypeSymbol> configs)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// This file is auto-generated by AsakiConfigRegistryGenerator. Do not modify manually.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Asaki.Unity.Services.DataTable;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using UnityEngine;"); // <-- 必须添加，用于 RuntimeInitializeOnLoadMethod
            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("using UnityEditor;"); // <-- 编辑器下 using，用于 InitializeOnLoadMethod
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine("namespace Asaki.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AsakiUserDataTableLoader");
            sb.AppendLine("    {");
            sb.AppendLine("        static AsakiUserDataTableLoader()");
            sb.AppendLine("        {");
            sb.AppendLine("            // 注册所有实现了 IAsakiDataTable 的配置类型");
            foreach (var config in configs)
            {
                string fullTypeName = config.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            AsakiConfigRegistry.RegisterLoader(");
                sb.AppendLine($"                typeof({fullTypeName}),");
                sb.AppendLine($"                (service, path) => service.LoadInternalAsync<{fullTypeName}>(path));");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        #if UNITY_EDITOR");
            sb.AppendLine("        [InitializeOnLoadMethod]");
            sb.AppendLine("        #endif");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void OnRuntimeInitialize() { }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}