using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

public static class AsakiBrokerGenerator
{
    private const string EVENT_INTERFACE_NAMESPACE = "Asaki.Core.Broker";
    private const string BROKER_FULL_NAME = "global::Asaki.Core.Broker.AsakiBroker";

    public static void Execute(
        GeneratorExecutionContext context,
        List<ClassDeclarationSyntax> handlerCandidates,
        List<MethodDeclarationSyntax> listenerCandidates)
    {
        var compilation = context.Compilation;
        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included
        );

        // ----- 1. 收集 Handler 类 -----
        var handlerMap = new Dictionary<INamedTypeSymbol, List<INamedTypeSymbol>>(SymbolEqualityComparer.Default);
        foreach (var syntax in handlerCandidates)
        {
            var model = compilation.GetSemanticModel(syntax.SyntaxTree);
            if (model == null) continue;
            
            var typeSymbol = model.GetDeclaredSymbol(syntax) as INamedTypeSymbol;
            if (typeSymbol == null || typeSymbol.IsAbstract) continue;

            var handlers = typeSymbol.AllInterfaces
                .Where(i => i.Name == "IAsakiHandler" && i.IsGenericType &&
                            i.ContainingNamespace.ToDisplayString() == EVENT_INTERFACE_NAMESPACE)
                .ToList();

            if (handlers.Count > 0 && !handlerMap.ContainsKey(typeSymbol))
                handlerMap[typeSymbol] = handlers;
        }

        // ----- 2. 收集 Listener 方法 -----
        var listenerMap = new Dictionary<INamedTypeSymbol, List<IMethodSymbol>>(SymbolEqualityComparer.Default);
        foreach (var syntax in listenerCandidates)
        {
            var model = compilation.GetSemanticModel(syntax.SyntaxTree);
            if (model == null) continue;
            
            var methodSymbol = model.GetDeclaredSymbol(syntax) as IMethodSymbol;
            if (methodSymbol == null) continue;

            if (!IsValidListenerMethod(methodSymbol, compilation))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("ASAKI002", "Invalid AsakiListener",
                        $"Method '{methodSymbol.Name}' is marked with [AsakiListener] but its signature is invalid. " +
                        "Must be: void MethodName(TEvent e) where TEvent : struct, IAsakiEvent",
                        "AsakiBroker", DiagnosticSeverity.Error, true),
                    syntax.GetLocation()));
                continue;
            }

            var containingType = methodSymbol.ContainingType;
            if (!listenerMap.ContainsKey(containingType))
                listenerMap[containingType] = new List<IMethodSymbol>();
            listenerMap[containingType].Add(methodSymbol);
        }

        if (handlerMap.Count == 0 && listenerMap.Count == 0)
            return;

        // ----- 3. 构建源代码 -----
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// 生成时间: {System.DateTime.Now.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Asaki.Generated");
        sb.AppendLine("{");
        GenerateSource(sb, handlerMap, listenerMap, format);
        sb.AppendLine("}");

        context.AddSource("AsakiBrokerExtensions.g.cs", sb.ToString());
    }

    private static bool IsValidListenerMethod(IMethodSymbol method, Compilation compilation)
    {
        if (!method.ReturnsVoid || method.Parameters.Length != 1)
            return false;

        var paramType = method.Parameters[0].Type;
        if (!paramType.IsValueType)
            return false;

        var eventInterface = compilation.GetTypeByMetadataName("Asaki.Core.Broker.IAsakiEvent");
        return eventInterface != null && paramType.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, eventInterface));
    }

    private static void GenerateSource(
        StringBuilder sb,
        Dictionary<INamedTypeSymbol, List<INamedTypeSymbol>> handlerMap,
        Dictionary<INamedTypeSymbol, List<IMethodSymbol>> listenerMap,
        SymbolDisplayFormat format)
    {
        sb.AppendLine("    internal static class AsakiBrokerExtensions");
        sb.AppendLine("    {");

        // ----- 生成适配器类 -----
        var generatedAdapters = new HashSet<string>();
        foreach (var kv in listenerMap)
        {
            foreach (var method in kv.Value)
            {
                var adapterName = $"{method.ContainingType.Name}_{method.Name}_Adapter";
                if (generatedAdapters.Add(adapterName))
                {
                    GenerateAdapter(sb, method, format, adapterName);
                }
            }
        }

        // ----- 生成缓存辅助类 -----
        GenerateCacheHelper(sb);

        // ----- 静态字典字段 -----
        sb.AppendLine("        private static readonly Dictionary<System.Type, System.Action<object>> _registerActions;");
        sb.AppendLine("        private static readonly Dictionary<System.Type, System.Action<object>> _unregisterActions;");
        sb.AppendLine();

        // ----- 静态构造函数 -----
        sb.AppendLine("        static AsakiBrokerExtensions()");
        sb.AppendLine("        {");
        sb.AppendLine("            _registerActions = new Dictionary<System.Type, System.Action<object>>();");
        sb.AppendLine("            _unregisterActions = new Dictionary<System.Type, System.Action<object>>();");
        sb.AppendLine();

        var allTypes = new HashSet<INamedTypeSymbol>(handlerMap.Keys, SymbolEqualityComparer.Default);
        foreach (var type in listenerMap.Keys)
            allTypes.Add(type);

        foreach (var type in allTypes)
        {
            var typeName = type.ToDisplayString(format);
            var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // ----- 注册委托 -----
            sb.AppendLine($"            // Register for {typeName}");
            sb.AppendLine($"            _registerActions[typeof({typeFullName})] = obj =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var target = ({typeName})obj;");

            if (handlerMap.TryGetValue(type, out var handlers))
            {
                foreach (var handler in handlers)
                {
                    var eventType = handler.TypeArguments[0].ToDisplayString(format);
                    sb.AppendLine($"                {BROKER_FULL_NAME}.Subscribe<{eventType}>(target);");
                }
            }

            if (listenerMap.TryGetValue(type, out var methods))
            {
                sb.AppendLine("                var cache = Cache.GetOrCreate(target);");
                foreach (var method in methods)
                {
                    var eventType = method.Parameters[0].Type.ToDisplayString(format);
                    var adapterName = $"{method.ContainingType.Name}_{method.Name}_Adapter";
                    var key = $"{method.ContainingType.Name}_{method.Name}_{eventType}";

                    sb.AppendLine($"                var adapter_{method.Name} = new {adapterName}(target);");
                    sb.AppendLine($"                cache[\"{key}\"] = adapter_{method.Name};");
                    sb.AppendLine($"                {BROKER_FULL_NAME}.Subscribe<{eventType}>(adapter_{method.Name});");
                }
            }

            sb.AppendLine("            };");
            sb.AppendLine();

            // ----- 注销委托 -----
            sb.AppendLine($"            // Unregister for {typeName}");
            sb.AppendLine($"            _unregisterActions[typeof({typeFullName})] = obj =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var target = ({typeName})obj;");

            if (handlers != null)
            {
                foreach (var handler in handlers)
                {
                    var eventType = handler.TypeArguments[0].ToDisplayString(format);
                    sb.AppendLine($"                {BROKER_FULL_NAME}.Unsubscribe<{eventType}>(target);");
                }
            }

            if (methods != null)
            {
                sb.AppendLine("                var cache = Cache.TryGet(target);");
                sb.AppendLine("                if (cache != null)");
                sb.AppendLine("                {");
                foreach (var method in methods)
                {
                    var eventType = method.Parameters[0].Type.ToDisplayString(format);
                    var key = $"{method.ContainingType.Name}_{method.Name}_{eventType}";

                    sb.AppendLine($"                    if (cache.TryGetValue(\"{key}\", out var adapter_{method.Name}))");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        {BROKER_FULL_NAME}.Unsubscribe<{eventType}>((global::{EVENT_INTERFACE_NAMESPACE}.IAsakiHandler<{eventType}>)adapter_{method.Name});");
                    sb.AppendLine($"                        cache.Remove(\"{key}\");");
                    sb.AppendLine("                    }");
                }
                sb.AppendLine("                }");
            }

            sb.AppendLine("            };");
            sb.AppendLine();
        }

        sb.AppendLine("        }"); // 结束静态构造函数
        sb.AppendLine();

        // ----- AsakiRegister -----
        sb.AppendLine("        internal static void AsakiRegister(this object obj)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_registerActions.TryGetValue(obj.GetType(), out var action))");
        sb.AppendLine("            {");
        sb.AppendLine("                action(obj);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ----- AsakiUnregister -----
        sb.AppendLine("        internal static void AsakiUnregister(this object obj)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_unregisterActions.TryGetValue(obj.GetType(), out var action))");
        sb.AppendLine("            {");
        sb.AppendLine("                action(obj);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ----- ClearCache (for hot reload / domain reload) -----
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Clears all cached registration actions. Call this during hot reload or domain reload scenarios.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        internal static void ClearCache()");
        sb.AppendLine("        {");
        sb.AppendLine("            _registerActions.Clear();");
        sb.AppendLine("            _unregisterActions.Clear();");
        sb.AppendLine("        }");

        sb.AppendLine("    }"); // 结束 AsakiBrokerExtensions
    }

    private static void GenerateAdapter(StringBuilder sb, IMethodSymbol method, SymbolDisplayFormat format, string adapterName)
    {
        var containingType = method.ContainingType.ToDisplayString(format);
        var eventType = method.Parameters[0].Type.ToDisplayString(format);

        sb.AppendLine($"        private sealed class {adapterName} : global::{EVENT_INTERFACE_NAMESPACE}.IAsakiHandler<{eventType}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            private readonly {containingType} _target;");
        sb.AppendLine($"            public {adapterName}({containingType} target) => _target = target;");
        sb.AppendLine($"            public void OnEvent({eventType} e) => _target.{method.Name}(e);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateCacheHelper(StringBuilder sb)
    {
        sb.AppendLine("        // ----- Listener adapter cache (ConditionalWeakTable) -----");
        sb.AppendLine("        private static class Cache");
        sb.AppendLine("        {");
        sb.AppendLine("            private static readonly ConditionalWeakTable<object, Dictionary<string, object>> _table");
        sb.AppendLine("                = new ConditionalWeakTable<object, Dictionary<string, object>>();");
        sb.AppendLine();
        sb.AppendLine("            public static Dictionary<string, object> GetOrCreate(object key)");
        sb.AppendLine("            {");
        sb.AppendLine("                return _table.GetOrCreateValue(key);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            public static Dictionary<string, object>? TryGet(object key)");
        sb.AppendLine("            {");
        sb.AppendLine("                _table.TryGetValue(key, out var dict);");
        sb.AppendLine("                return dict;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            public static void Remove(object key)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_table.TryGetValue(key, out var dict))");
        sb.AppendLine("                {");
        sb.AppendLine("                    dict.Clear();");
        sb.AppendLine("                    _table.Remove(key);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
}