using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Asaki.CodeGen.Generators
{
    public static class AsakiInjectGenerator
    {
        public static void Execute(
            GeneratorExecutionContext context,
            List<MethodDeclarationSyntax> candidates
        )
        {
            if (candidates == null || candidates.Count == 0)
                return;

            var compilation = context.Compilation;
            var attributeSymbol = compilation.GetTypeByMetadataName(
                "Asaki.Core.Attributes.AsakiInjectAttribute"
            );
            if (attributeSymbol == null)
                return;

            // 筛选有效方法
            var validMethods = new List<(MethodDeclarationSyntax Syntax, IMethodSymbol Symbol)>();
            foreach (var methodDeclaration in candidates)
            {
                var model = compilation.GetSemanticModel(methodDeclaration.SyntaxTree);
                var methodSymbol = model.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
                if (methodSymbol == null)
                    continue;

                if (
                    methodSymbol
                        .GetAttributes()
                        .Any(ad =>
                            SymbolEqualityComparer.Default.Equals(
                                ad.AttributeClass,
                                attributeSymbol
                            )
                        )
                )
                {
                    validMethods.Add((methodDeclaration, methodSymbol));
                }
            }

            if (validMethods.Count == 0)
                return;

            // 开始生成
            string assemblyNameSafe = context
                .Compilation.AssemblyName.Replace(".", "_")
                .Replace("-", "_");
            string className = $"AsakiAssemblyInjector_{assemblyNameSafe}";
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Asaki.Core.Context;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Asaki.Generated.Injectors");
            sb.AppendLine("{");
            sb.AppendLine(
                $"    /// <summary> 程序集专用注入器 (O(1) Dictionary Lookup): {context.Compilation.AssemblyName} </summary>"
            );
            sb.AppendLine($"    public class {className} : IAsakiInjector");
            sb.AppendLine("    {");

            // 1. 静态字典存储注入逻辑
            sb.AppendLine(
                "        private static readonly Dictionary<Type, Action<object, IAsakiResolver>> _injectMap = new Dictionary<Type, Action<object, IAsakiResolver>>();"
            );
            sb.AppendLine();

            // 2. 静态构造/初始化
            sb.AppendLine("        static " + className + "()");
            sb.AppendLine("        {");
            foreach (var pair in validMethods)
            {
                var methodSymbol = pair.Symbol;
                var classSymbol = methodSymbol.ContainingType;
                string fullClassName = classSymbol.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat
                );
                string methodName = methodSymbol.Name;

                sb.Append(
                    $"            _injectMap[typeof({fullClassName})] = (target, resolver) => (({fullClassName})target).{methodName}("
                );

                var parameters = methodSymbol.Parameters;
                for (int i = 0; i < parameters.Length; i++)
                {
                    var paramType = parameters[i].Type;
                    string fullParamTypeName = paramType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    );
                    sb.Append($"resolver.Get<{fullParamTypeName}>()");
                    if (i < parameters.Length - 1)
                        sb.Append(", ");
                }
                sb.AppendLine(");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. 自动注册
            sb.AppendLine(
                "        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]"
            );
            sb.AppendLine("        private static void AutoRegister()");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            global::Asaki.Unity.Bootstrapper.AsakiGlobalInjector.Register(new {className}());"
            );
            sb.AppendLine("        }");
            sb.AppendLine();

            // 4. 接口实现 (O(1) 查找)
            sb.AppendLine(
                "        public void Inject(object target, IAsakiResolver resolver = null)"
            );
            sb.AppendLine("        {");
            sb.AppendLine("            if (target == null) return;");
            sb.AppendLine(
                "            if (resolver == null) resolver = global::Asaki.Core.Context.Resolvers.AsakiGlobalResolver.Instance;"
            );
            sb.AppendLine();
            sb.AppendLine(
                "            if (_injectMap.TryGetValue(target.GetType(), out var action))"
            );
            sb.AppendLine("            {");
            sb.AppendLine("                action(target, resolver);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{className}.g.cs", sb.ToString());
        }
    }
}
