using Asaki.Core;
using Asaki.Core.Attributes;
using Asaki.Core.Context;
using Asaki.Core.DataTable;
using Asaki.Core.Logging;
using UnityEngine;

namespace Asaki.Unity.Services.Scene.SceneManagement.Test
{
    [AsakiSave]
    public partial class AsakiWeaponDataTableExample : IAsakiDataTable
    {
        [AsakiSaveMember]
        public int Id { get; set; }

        [AsakiSaveMember]
        public string WeaponAssetPath { get; set; }
    }

    /*
    // <auto-generated/>
    // 生成时间: 12/22/2025 19:32:24
    using Asaki.Core.Serialization;
    using UnityEngine;
    using System.Collections.Generic;
    using System;

    namespace Game.Test
    {
        partial class AsakiWeaponDataTableExample : IAsakiSavable
        {
            // WARNING: This is a configuration type. Direct serialization is restricted for safety.
            private bool _allowConfigSerialization = false;

            /// <summary>
            /// Internal method to enable config serialization. This should ONLY be called by the config system.
            /// </summary>
            internal void AllowConfigSerialization(bool allow = true)
            {
                _allowConfigSerialization = allow;
            }

            public void Serialize(IAsakiWriter writer)
            {
                // SECURITY CHECK: Prevent accidental serialization of config objects
                if (!_allowConfigSerialization)
                {
                    throw new InvalidOperationException("Security violation: Attempt to serialize configuration object 'AsakiWeaponDataTableExample'. " +
                        "DataTable objects should NEVER be saved in game saves. " +
                        "Instead, save only the configuration ID and reload the config when needed.");
                }

                writer.BeginObject("AsakiWeaponDataTableExample");
                writer.WriteInt("Id", this.Id);
                writer.WriteString("WeaponAssetPath", this.WeaponAssetPath);
                writer.EndObject();
            }

            public void Deserialize(IAsakiReader reader)
            {
                this.Id = reader.ReadInt("Id");
                this.WeaponAssetPath = reader.ReadString("WeaponAssetPath");
            }
        }
    }

     */

    public class ConfigExample : MonoBehaviour
    {
        [ContextMenu("Queries")]
        public void Query()
        {
            var weapon = AsakiContext
                .Get<IAsakiConfigService>()
                .Get<AsakiWeaponDataTableExample>(0);
            if (weapon != null)
            {
                ALog.Info(weapon.WeaponAssetPath);
            }
            else
            {
                ALog.Warn("Weapon config not found.");
            }
            ALog.Info("Weapon config queried.");
        }
    }
}
